### ISSUE TITLE
Extend the predict function to a general multiclass problem

### ISSUE THREAD

**Issue by MinhHuong** [MinhHuong/Stream_mining_project#1]
The predict function should be able to process the general case of multiclass classification problem. The function `predict` is to be implemented accordingly to this idea.

**Comment by MinhHuong** [comment]
This max votes prediction will be implemented in `WeightedEnsembleClassifier::predict`

**Comment by armitakhn** [comment]
I think it's solved

**Comment by soum-kd** [comment]
we are not suppose to do a  multilabel + multiclass problem right ?

**Comment by MinhHuong** [comment]
@soum-kd Yeah that will be an interesting extension. We only have to focus on multiclass/multilabel now (one target with many possible labels). We can take care of the multi-output (many targets) later 😃
