### ISSUE TITLE
Implement instance-based pruning

### ISSUE THREAD

**Issue by MinhHuong** [MinhHuong/Stream_mining_project#2]
Algorithm 1 (already implemented in `partial_fit`) needs to be extended to take into account instance-based pruning, which aims to reduce the number of classifiers to a subset of size k << K needed for prediction while ensuring convergence to the same result as if using K classifiers.

**Comment by soum-kd** [comment]
it remains a binary classification (for example 1: fraud, 0: not fraud) we'lll basically use only the probability of classifying x as 1  in the weughted probability

**Comment by MinhHuong** [comment]
This should be implemented in `CostSensitiveWeightedEnsemble::partial_fit`` (at the end of this function). The code should follow what has been described in Algorithm 2 in the paper.
