### ISSUE TITLE
Allows the ensemble to take into account cost-sensitive applications

### ISSUE THREAD

**Issue by MinhHuong** [MinhHuong/Stream_mining_project#4]
Users should be able to adapt the ensemble classifier to their need of having a cost-sensitive classifier. That is, to switch the computation of weight and benefit according to their specific applications.

This should be first done by accepting more arguments when initializing the ensemble, e.g. `WeightedEnsembleClassifier(cost_sensitive=True)`

**Comment by soum-kd** [comment]
it remains a binary classification (for example 1: fraud, 0: not fraud) we'lll basically use only the probability of classifying x as 1 in the weighted probability

**Comment by MinhHuong** [comment]
Oops I'd opened this issue before I introduced the class `CostSensitiveWeightedEnsemble`. Since this idea is outdated I'll close this issue now.
