### ISSUE TITLE
Implement the predict function given in Algorithm 3

### ISSUE THREAD

**Issue by MinhHuong** [MinhHuong/Stream_mining_project#5]
Algorithm 3 proposes the classification process applied to cost-sensitive applications (a binary classification problem, let's consider it as such for simplicity). We need to implement `predict` in `CostSensitiveWeightedEnsembleClassifier` following the pseudo-code in Algorithm 3.

**Comment by soum-kd** [comment]
i use the credictcard.csv dataset from kaggle for cost sensitive applications it is unbalanced and i compute the confusion matrix
